# Generated by Django 2.2.6 on 2019-11-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companiseimages',
            old_name='companise',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='companiseimages',
            old_name='company_img',
            new_name='company_image',
        ),
    ]
