# Generated by Django 2.2.6 on 2019-11-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companiesimages',
            old_name='companies',
            new_name='company',
        ),
    ]
