# Generated by Django 2.2.6 on 2019-10-31 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompaniseImgs',
            new_name='CompaniseImages',
        ),
        migrations.AlterModelTable(
            name='companiseimages',
            table='companise_images',
        ),
    ]
