# Generated by Django 2.2.6 on 2019-11-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompaniseImages',
            new_name='CompaniesImages',
        ),
    ]
