# Generated by Django 2.2.6 on 2019-10-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20191031_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companise',
            name='lat',
            field=models.DecimalField(decimal_places=30, max_digits=35, null=True),
        ),
        migrations.AlterField(
            model_name='companise',
            name='lng',
            field=models.DecimalField(decimal_places=30, max_digits=35, null=True),
        ),
    ]
