# Generated by Django 2.2.6 on 2019-11-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_Portfolio',
            new_name='Portfolio',
        ),
        migrations.RenameModel(
            old_name='Saving_Types',
            new_name='SavingTypes',
        ),
        migrations.AlterField(
            model_name='projects',
            name='github',
            field=models.URLField(max_length=3000),
        ),
    ]
