# Generated by Django 2.2.6 on 2019-11-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20191105_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='blog',
            field=models.URLField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='portfolio',
            table='portfolio',
        ),
        migrations.AlterModelTable(
            name='projects',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='resume',
            table='resume',
        ),
        migrations.AlterModelTable(
            name='savingtypes',
            table='savingtypes',
        ),
    ]
