# Generated by Django 2.2.6 on 2019-11-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=1000, null=True)),
                ('intro', models.TextField(null=True)),
                ('main_tasks', models.TextField(null=True)),
                ('requirements', models.TextField(null=True)),
                ('preferred_points', models.TextField(null=True)),
                ('benefits', models.TextField(null=True)),
                ('dead_line', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Categories')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Companies')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='JobsToTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Jobs')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Tags')),
            ],
            options={
                'db_table': 'jobs_to_tags',
            },
        ),
        migrations.AddField(
            model_name='jobs',
            name='tags',
            field=models.ManyToManyField(through='job.JobsToTags', to='job.Tags'),
        ),
    ]
